version: '3.8'

services:

    microservice:
        build:
            context: .
        restart: always

    nginx-balancer:
        build: ./nginx
        image: nginx
        container_name: nginx-balancer
        restart: always

        depends_on:
            - microservice
        ports:
            - "8000:8000"


#version: '3.8'

#services:

  # app1:
  #   build: .
  #   expose:
  #     - 8000

  # app2:
  #   build: .
  #   expose:
  #     - 8000

  # nginx:
  #   build: ./nginx
  #   ports:
  #   - "8000:80"
  #   depends_on:
  #     - app1
  #     - app2



#    volumes:
#            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro