version: '3.8'

services:



    nginx-balancer:
        build: ./nginx
        image: nginx
        container_name: nginx-balancer
        restart: always
        ports:
            - "8000:8000"


#version: '3.8'

#services:

  # app1:
  #   build: .
  #   expose:
  #     - 8000

  # app2:
  #   build: .
  #   expose:
  #     - 8000

  # nginx:
  #   build: ./nginx
  #   ports:
  #   - "8000:80"
  #   depends_on:
  #     - app1
  #     - app2



#    volumes:
#            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro